name: Build and Publish Containerized Version of Website 
  
on:
  push: 
    branches: [ "test" ] 
  
jobs:
   Build_and_Push_to_Docker_Hub: 
     name: Build Docker image and push it to Docker Hub 
     runs-on: ubuntu-latest 
     permissions: 
       packages: write 
       contents: read 
     steps: 
       - name: Check out the repo 
         uses: actions/checkout@v3 
  
       - name: Log in to Docker Hub 
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a 
         with: 
           username: ${{ secrets.DOCKER_USERNAME }} 
           password: ${{ secrets.DOCKER_PASSWORD }} 
  
       - name: Extract metadata (tags, labels) for Docker 
         id: meta 
         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7 
         with: 
           images: | 
             paulrosenthal/sea-florida-change-website 
        
       - name: Build Image and Publish to Docker Hub 
         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 
         with: 
           context: . 
           push: true 
           tags: ${{ steps.meta.outputs.tags }} 
           labels: ${{ steps.meta.outputs.labels }} 
  
   Google_Cloud_Deploy:  
      needs: Build_and_Push_to_Docker_Hub 
      runs-on: ubuntu-latest  
      permissions:  
        contents: 'read'  
        id-token: 'write'  
  
      steps:  
      - uses: 'actions/checkout@v3'  
  
      - name: 'Authenticate to Google Cloud'  
        uses: 'google-github-actions/auth@v1'  
        with:  
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}   
  
      - name: 'Set up Cloud SDK'  
        uses: 'google-github-actions/setup-gcloud@v1'  
        with:  
          version: '>= 363.0.0'  
  
      - name: 'Execute Deploy to Test Environment'  
        run: 'gcloud config set run/region us-central1 && gcloud run deploy sea-florida-change-website-test --image=index.docker.io/paulrosenthal/sea-florida-change-website:test --region=us-central1 --project=sea-florida-change && gcloud run services update-traffic sea-florida-change-website-test --to-latest' 
