name: Continuous Integration Tests

on: [push]

jobs:
  Jekyll-Deploy:
    runs-on: ubuntu-latest
    name: Jekyll Deployment Test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Jekyll Deploy Test
      uses: PaulRosenthal/Jekyll-Deploy-Test-Action@v2
    - name: Upload _site Directory From Test Build
      uses: actions/upload-artifact@v3
      with:
        name: test_site_directory
        path: _site
  Execute-RSpec-Tests:
    runs-on: ubuntu-latest
    needs: Jekyll-Deploy
    name: Execute RSpec Tests
    steps:
    - name: Download _site Directory From Test Build
      uses: actions/download-artifact@v3
      with:
        name: test_site_directory
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Prepare Environment to Run Tests
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: false
    - name: Run RSpec Tests 
      run: bundle install && rspec spec --format documentation --out rspec_tests_output.txt
    - name: Upload RSpec Tests Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: rspec_tests_results
        path: rspec_tests_output.txt
