name: Production Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  Google_Cloud_Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }} 
        
    - name: Deploy to Google Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'sea-florida-change-website-production'
        image: 'index.docker.io/paulrosenthal/sea-florida-change-website:main'
